version: "3"

dotenv: ["build.env"]

vars:
  gobin: go
  ldflags: "-extldflags '-static' -w -s -buildid="
  gcflags: "all=-trimpath={{.PWD}} -dwarf=false -l"
  asmflags: "all=-trimpath={{.PWD}}"
  bin: "{{.PWD}}/bin"
  app: "trans"
  app_bin: "{{.bin}}/{{.app}}"

env:
  COMPOSE_BAKE: true
  CGO_ENABLED: 0
  GOARCH: amd64
  GOOS: linux

tasks:
  setup:
    desc: set up the environment
    silent: true
    cmds:
      - mkdir -p {{.bin}}

  build:
    desc: common build
    deps:
      - setup
    cmds:
      - >
        {{.gobin}} build
        -tags netgo
        -ldflags="{{.ldflags}}"
        -trimpath
        -gcflags="{{.gcflags}}"
        -asmflags="{{.asmflags}}"
        -o {{.app_bin}} cmd/{{.app}}/main.go
      - strip {{.app_bin}}
      - objcopy --strip-unneeded {{.app_bin}}

  in-docker-build:
    deps:
      - build
    silent: false
    cmds:
      - rm -f /build/bin/*
      - upx --best --ultra-brute {{.app_bin}} -o {{.app_bin}}_upx
      - mv {{.app_bin}}* /build/bin

  docker.build:
    desc: build bin via docker
    deps:
      - setup
    silent: false
    cmds:
      - docker compose -f docker-compose.build.yaml up --build --force-recreate
